const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const menu=document.querySelector('.menu-toggle'), nav=document.querySelector('nav');
menu?.addEventListener('click',()=>{nav.classList.toggle('open');menu.textContent=nav.classList.contains('open')?'✕':'☰'});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.services,.inventory,.service-band,.process,.contact,.service-grid article,.machine-card,.steps>div').forEach(el=>{el.classList.add('reveal');io.observe(el)});
const field=document.querySelector('#dust-field');
if(field&&!reduce){for(let i=0;i<32;i++){const mote=document.createElement('i');mote.className='dust-mote';const size=4+Math.random()*22;mote.style.width=`${size}px`;mote.style.height=`${size}px`;mote.style.left=`${Math.random()*100}%`;mote.style.top=`${35+Math.random()*60}%`;mote.style.setProperty('--x',`${-80+Math.random()*180}px`);mote.style.setProperty('--y',`${-80-Math.random()*180}px`);mote.style.animationDuration=`${7+Math.random()*11}s`;mote.style.animationDelay=`-${Math.random()*12}s`;field.appendChild(mote)}}
const counters=document.querySelectorAll('[data-count]');const countIO=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const target=+e.target.dataset.count;let start=0;const tick=()=>{start+=Math.max(1,Math.ceil(target/30));e.target.textContent=Math.min(start,target);if(start<target)requestAnimationFrame(tick)};tick();countIO.unobserve(e.target)}}),{threshold:.7});counters.forEach(c=>countIO.observe(c));
window.addEventListener('mousemove',e=>{if(reduce)return;const x=(e.clientX/innerWidth-.5)*12,y=(e.clientY/innerHeight-.5)*8;document.querySelector('.excavator-stage')?.style.setProperty('transform',`translate(${x}px,${y}px)`)});
